### PR TITLE
make noarch

### PR DESCRIPTION
**Pull request by martindurant**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martindurant** [comment]
@conda-forge-admin, please rerender

**Comment by martindurant** [comment]
Fixes #5 (with any luck)

**Comment by martindurant** [comment]
@conda-forge/core , I don't know what the message above means. I am trying to make this package noarch, since the py37/linux build failed, some time ago, but the source is pure-python.

**Comment by mariusvniekerk** [comment]
@conda-forge-admin, please rerender

**Comment by mariusvniekerk** [comment]
rerender bot was a little weird, kicked it and it should be fine now

**Comment by martindurant** [comment]
Thanks, @mariusvniekerk

**Pull request merged**
